// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TecWi_Web.Data.Context;

namespace TecWi_Web.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210904013331_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Cdclifor")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inscrifed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cdclifor");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.PagarReceber", b =>
                {
                    b.Property<string>("Numlancto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sq")
                        .HasColumnType("int");

                    b.Property<string>("Cdfilial")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cdclifor")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dtemissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dtpagto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dtvencto")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotasFiscais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeqID")
                        .HasColumnType("int");

                    b.Property<bool>("Stcobranca")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valorr")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Numlancto", "Sq", "Cdfilial");

                    b.HasIndex("Cdclifor");

                    b.ToTable("PagarReceber");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.UsuarioAplicacao", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdAplicacao", "IdPerfil");

                    b.ToTable("UsuarioAplicacao");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.PagarReceber", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Cliente", "Cliente")
                        .WithMany("PagarReceber")
                        .HasForeignKey("Cdclifor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.UsuarioAplicacao", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioAplicacao")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("PagarReceber");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioAplicacao");
                });
#pragma warning restore 612, 618
        }
    }
}
