// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TecWi_Web.Data.Context;

namespace TecWi_Web.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220129230658_Add_Table_Pedido_PedidoItem")]
    partial class Add_Table_Pedido_PedidoItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Cdclifor")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Inscrifed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cdclifor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.ClienteContato", b =>
                {
                    b.Property<Guid>("IdClienteContato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cdclifor")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Nome")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdClienteContato");

                    b.HasIndex("Cdclifor");

                    b.ToTable("ClienteContato");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.ContatoCobranca", b =>
                {
                    b.Property<Guid>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anotacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cdclifor")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtAgenda")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtContato")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoContato")
                        .HasColumnType("int");

                    b.HasKey("IdContato");

                    b.HasIndex("Cdclifor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ContatoCobranca");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.ContatoCobrancaLancamento", b =>
                {
                    b.Property<Guid>("IdContato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numlancto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sq")
                        .HasColumnType("int");

                    b.Property<string>("CdFilial")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("UsuarioIdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdContato", "Numlancto", "Sq", "CdFilial");

                    b.HasIndex("UsuarioIdUsuario");

                    b.HasIndex("Numlancto", "Sq", "CdFilial");

                    b.ToTable("ContatoCobrancaLancamento");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.LogOperacao", b =>
                {
                    b.Property<Guid>("IdLogOperacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("int");

                    b.HasKey("IdLogOperacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LogOperacao");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.LogSincronizacaoProdutoMercoCamp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InicioSincronizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonEnvio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodoFinalEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodoInicialEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("LogSincronizacaoProdutoMercoCamp");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.PagarReceber", b =>
                {
                    b.Property<string>("Numlancto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sq")
                        .HasColumnType("int");

                    b.Property<string>("Cdfilial")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cdclifor")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dtemissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dtpagto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dtvencto")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotasFiscais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumTransf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeqID")
                        .HasColumnType("int");

                    b.Property<bool>("Stcobranca")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valorr")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Numlancto", "Sq", "Cdfilial");

                    b.HasIndex("Cdclifor");

                    b.ToTable("PagarReceber");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.ParametroSincronizacaoProduto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataHoraSincronizacao")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UltimoUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ParametroSincronizacaoProduto");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cdcliente")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("cdempresa")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("cdfilial")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("cdtransportadora")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("cdtransportadoraredespacho")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("cdvendedor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("dtinicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nummovcliente")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("nummovimento")
                        .HasColumnType("int");

                    b.Property<string>("stpagafrete")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stpagafreteredespacho")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stpendencia")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDPedido")
                        .HasColumnType("int");

                    b.Property<decimal?>("VlVenda")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<string>("cdempresa")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("cdfilial")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("cdproduto")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("nummovimento")
                        .HasColumnType("int");

                    b.Property<decimal?>("qtdprocessada")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("qtdsolicitada")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<int>("seq")
                        .HasColumnType("int");

                    b.Property<string>("tpregistro")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("uporigem")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("vlcalculado")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.HasKey("ID");

                    b.HasIndex("IDPedido");

                    b.ToTable("PedidoItem");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Produto", b =>
                {
                    b.Property<string>("VersionId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CdProduto")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CdEmpresa")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CdFilial")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Aduana")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("AlqICMS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AlqICMSCPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AlqIPI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AlqIPICPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AlqImportacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AreaEnvolvimento")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Campo01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campo06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdBarra")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CdCelula")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CdClasFiscal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CdClassTox")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CdClasse")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CdClassifFinanc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CdClassifFinancCpr")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CdContabil")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CdContabilCpr")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CdFornecPadrao")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CdGrade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CdGrupo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CdGrupoQuimico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdOld")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CdProdutoIndustrializacao")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CdServicoIndustrializacao")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CdStTributaria")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CdUPPickingArea")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CdUnidadeVolume")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Concentracao")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("ConsumoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DsCompra")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DsHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsVenda")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("DtCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDesativado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtRefCustoComposicaoSTD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtRefCustoServico")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtRefCustoServicoSTD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtRefCustoStandard")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtRefVlSugerido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtRefVlSugeridoSTD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUltCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUltCustoComposicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EPI_CertificadoAprovacao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EPI_QtdVidaUtil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPI_UnidadeVidaUtil")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailInventario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Embalagem")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Estante")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<float?>("EstoqEstrategico")
                        .HasColumnType("real");

                    b.Property<float?>("EstoqMax")
                        .HasColumnType("real");

                    b.Property<float?>("EstoqMin")
                        .HasColumnType("real");

                    b.Property<float?>("EstoqReposicao")
                        .HasColumnType("real");

                    b.Property<decimal?>("EstoqueSeguranca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GeraSolOC")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("GiroEstoque")
                        .HasColumnType("int");

                    b.Property<string>("IndiceCustoComposicao")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("IndiceCustoComposicaoSTD")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("IndiceCustoR")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("IndiceCustoServico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndiceCustoServicoSTD")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("IndiceCustoStandard")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("IndiceVendaR")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("LeadTime")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<int?>("LifeCycle")
                        .HasColumnType("int");

                    b.Property<string>("ListaProdAssociado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LoteMinimo")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("Marca")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("MargemLucro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MarkUp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nivel")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("NivelEstrutura")
                        .HasColumnType("int");

                    b.Property<string>("NotaMinimaCQ")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NumDespacho")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("NumDiasGarantia")
                        .HasColumnType("int");

                    b.Property<string>("NumRevisao")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("OpcCtsToleranciaVlCompra")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Origem")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OrigemLinhaProducao")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OrigemMercadoria")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("PaisOrigem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PathNomeScrGeraNumSerie")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PendenteProcesNivelEstrutura")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("PerMaoObra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PercComissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PercDespesaFixa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PercDesvioInferior")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal?>("PercDesvioInferior2")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal?>("PercDesvioInferior3")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal?>("PercDesvioInferiorcpr")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PercDesvioSuperior")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal?>("PercDesvioSuperior2")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal?>("PercDesvioSuperior3")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal?>("PercDesvioSuperiorcpr")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PercEncargoFinanc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PercFrete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PercMargContribuicao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PercOutrasDespesas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PercPromocao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PercToleranciaVlCompra")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<int?>("PeriodInventario")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoBruto")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("PesoLiq")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("PickingAmountMin_Unit")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("PickingAreaAmountLot")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("PickingAreaAmountMin")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("PickingAreaAmountMin_Unit")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PoliticaLote")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("PrazoValidade")
                        .HasColumnType("int");

                    b.Property<decimal?>("QtdAguardEntrega")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("QtdAtualR")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("QtdEmpenhada")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<int?>("QtdItem")
                        .HasColumnType("int");

                    b.Property<string>("Setor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("SkipLoteProducao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("StAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("StBloqueioInventario")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StCertificado")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StComposedKit")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StConsisteEstoque")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("StDel")
                        .HasColumnType("int");

                    b.Property<bool?>("StDesconto")
                        .HasColumnType("bit");

                    b.Property<string>("StDisponivelSFA")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("StEDI")
                        .HasColumnType("bit");

                    b.Property<string>("StEPI")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StExigeNumSerie")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StGeraNumSerie")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("StGerarFichaMPSAutomaticamente")
                        .HasColumnType("bit");

                    b.Property<string>("StIPIAlq_Prd")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StImpostoZonaFranca")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StIntegratePickingArea")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StJumpPacking")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("StKit")
                        .HasColumnType("bit");

                    b.Property<string>("StMultiploPreDefinido")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StPCP")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StPrePedido")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StProdutoFantasma")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("StTabelaPreco")
                        .HasColumnType("bit");

                    b.Property<string>("StToleranciaCompraBloqueio")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StTpControle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StUpd")
                        .HasColumnType("int");

                    b.Property<string>("SubUpInspecao")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal?>("TempoMedioProducao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TempoReposicao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCustoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TpNivelEstoqPCP")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TpProduto")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TpTributacao")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("UPEstocagem")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UPEstocagemPCP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UPProducao2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UPProducao3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UPProducao4")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UPProducao5")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UPProducao6")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UltDtInventario")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnidConsMedio")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UnidLeadTime")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("UnidTempoMedio")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Unidade")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UnidadePeso")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UnidadeVda")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UpInspecao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("ValorCustoR")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("ValorVarejo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorVendaR")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<DateTime?>("VersionCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionEffectiveByUser")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("VersionEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("VlCustoComposicao")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("VlCustoComposicaoSTD")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("VlCustoMedio")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("VlCustoMedioComposicao")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("VlCustoMedioServico")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("VlCustoMedioServicoCD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VlCustoMedioServicoCIF")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("VlCustoMedioServicoCSub")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("VlCustoServico")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("VlCustoServicoCD")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("VlCustoServicoCIF")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("VlCustoServicoCSub")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("VlCustoServicoSTD")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal?>("VlCustoStandard")
                        .HasPrecision(19, 10)
                        .HasColumnType("decimal(19,10)");

                    b.Property<decimal?>("VlMercado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VlSugestaoVda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VlSugestaoVdaSTD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("cdcest")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("cdenquadramentolegalipi")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("cdenquadramentolegalipi2")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("cdsttributaria2")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("cdsttributariacofins")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("cdsttributariacofins2")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("cdsttributariaipi")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("cdsttributariaipi2")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("cdsttributariapis")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("cdsttributariapis2")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("dsdumping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsespanhol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsingles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dtconsisteestoque")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtexigenumserie")
                        .HasColumnType("datetime2");

                    b.Property<string>("epi_pathdoctreinamento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("extipi")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("historiconf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ipi_nt")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("keypaf")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ncm")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("opcpromocao")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("politicaConsumoLote")
                        .HasColumnType("int");

                    b.Property<string>("politicamanufatura")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("qtdvolume")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<byte[]>("rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("sfaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("stativo02")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stativo03")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stdumping")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stexigelote")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("sticms_compra")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stipi_compra")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stli")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stopcional")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("stsubup")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("stupdSFA")
                        .HasColumnType("int");

                    b.Property<string>("subupestocagem")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("subupestocagempcp")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("subupproducao")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("updregistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("vlicms_compra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("vlipi_compra")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VersionId", "CdProduto", "CdEmpresa", "CdFilial");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.UsuarioAplicacao", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdAplicacao")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<bool>("StAtivo")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuario", "IdAplicacao", "IdPerfil");

                    b.ToTable("UsuarioAplicacao");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Cliente")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.ClienteContato", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Cliente", "Cliente")
                        .WithMany("ClienteContato")
                        .HasForeignKey("Cdclifor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.ContatoCobranca", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Cliente", "Cliente")
                        .WithMany("ContatoCobranca")
                        .HasForeignKey("Cdclifor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TecWi_Web.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ContatoCobranca")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.ContatoCobrancaLancamento", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.ContatoCobranca", "ContatoCobranca")
                        .WithMany("ContatoCobrancaLancamento")
                        .HasForeignKey("IdContato")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TecWi_Web.Domain.Entities.Usuario", null)
                        .WithMany("ContatoCobrancaLancamento")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.HasOne("TecWi_Web.Domain.Entities.PagarReceber", "PagarReceber")
                        .WithMany("ContatoCobrancaLancamento")
                        .HasForeignKey("Numlancto", "Sq", "CdFilial")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContatoCobranca");

                    b.Navigation("PagarReceber");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.LogOperacao", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Usuario", "Usuario")
                        .WithMany("LogOperacao")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.PagarReceber", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Cliente", "Cliente")
                        .WithMany("PagarReceber")
                        .HasForeignKey("Cdclifor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Pedido", "Pedido")
                        .WithMany("PedidoItem")
                        .HasForeignKey("IDPedido")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.UsuarioAplicacao", b =>
                {
                    b.HasOne("TecWi_Web.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioAplicacao")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ClienteContato");

                    b.Navigation("ContatoCobranca");

                    b.Navigation("PagarReceber");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.ContatoCobranca", b =>
                {
                    b.Navigation("ContatoCobrancaLancamento");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.PagarReceber", b =>
                {
                    b.Navigation("ContatoCobrancaLancamento");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("TecWi_Web.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("ContatoCobranca");

                    b.Navigation("ContatoCobrancaLancamento");

                    b.Navigation("LogOperacao");

                    b.Navigation("UsuarioAplicacao");
                });
#pragma warning restore 612, 618
        }
    }
}
