using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace TecWi_Web.Data.Migrations
{
    public partial class Add_Tabelas_Sincronizacao_E_Produto : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ParametroSincronizacaoProduto",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    DataHoraSincronizacao = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UltimoUpdateDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ParametroSincronizacaoProduto", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "Produto",
                columns: table => new
                {
                    CdEmpresa = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    CdFilial = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: false),
                    CdProduto = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: false),
                    VersionId = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    DsVenda = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    DsCompra = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    CdClassifFinanc = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    Unidade = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    CdStTributaria = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    TpTributacao = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    CdClasFiscal = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    CdOld = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CdBarra = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    PesoBruto = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    PesoLiq = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    UnidadePeso = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    qtdvolume = table.Column<decimal>(type: "decimal(8,2)", precision: 8, scale: 2, nullable: true),
                    StAtivo = table.Column<bool>(type: "bit", nullable: true),
                    StDesconto = table.Column<bool>(type: "bit", nullable: true),
                    StEDI = table.Column<bool>(type: "bit", nullable: true),
                    StKit = table.Column<bool>(type: "bit", nullable: true),
                    UnidadeVda = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    Origem = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    TpProduto = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    DtCadastro = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DtDesativado = table.Column<DateTime>(type: "datetime2", nullable: true),
                    QtdItem = table.Column<int>(type: "int", nullable: true),
                    Setor = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    Estante = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    Nivel = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CdGrupo = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    StTabelaPreco = table.Column<bool>(type: "bit", nullable: true),
                    ConsumoMedio = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnidConsMedio = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    EstoqMin = table.Column<float>(type: "real", nullable: true),
                    EstoqMax = table.Column<float>(type: "real", nullable: true),
                    EstoqEstrategico = table.Column<float>(type: "real", nullable: true),
                    EstoqReposicao = table.Column<float>(type: "real", nullable: true),
                    QtdAtualR = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    TempoMedioProducao = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnidTempoMedio = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PercDesvioInferior = table.Column<decimal>(type: "decimal(8,3)", precision: 8, scale: 3, nullable: true),
                    PercDesvioSuperior = table.Column<decimal>(type: "decimal(8,3)", precision: 8, scale: 3, nullable: true),
                    PercComissao = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MargemLucro = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PercOutrasDespesas = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PercEncargoFinanc = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PercFrete = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PerMaoObra = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VlCustoMedio = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    AlqICMS = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AlqICMSCPA = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AlqIPI = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AlqIPICPA = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AlqImportacao = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    IndiceCustoR = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    IndiceVendaR = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    ValorCustoR = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    ValorVendaR = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    ValorVarejo = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TotalCustoMedio = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Marca = table.Column<string>(type: "nvarchar(15)", maxLength: 15, nullable: true),
                    NumDespacho = table.Column<string>(type: "nvarchar(15)", maxLength: 15, nullable: true),
                    Aduana = table.Column<string>(type: "nvarchar(15)", maxLength: 15, nullable: true),
                    PaisOrigem = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    OrigemLinhaProducao = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    AreaEnvolvimento = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    CdCelula = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    NumDiasGarantia = table.Column<int>(type: "int", nullable: false),
                    VlSugestaoVda = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MarkUp = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PercDespesaFixa = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PercMargContribuicao = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VlMercado = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    GiroEstoque = table.Column<int>(type: "int", nullable: true),
                    CdClassifFinancCpr = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    CdClasse = table.Column<string>(type: "nvarchar(15)", maxLength: 15, nullable: true),
                    CdGrupoQuimico = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CdClassTox = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    Concentracao = table.Column<string>(type: "nvarchar(15)", maxLength: 15, nullable: true),
                    PercPromocao = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    opcpromocao = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    VlCustoServico = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    IndiceCustoServico = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Embalagem = table.Column<string>(type: "nvarchar(15)", maxLength: 15, nullable: true),
                    StExigeNumSerie = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    CdContabil = table.Column<string>(type: "nvarchar(7)", maxLength: 7, nullable: true),
                    StPrePedido = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    DtUltCompra = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CdFornecPadrao = table.Column<string>(type: "nvarchar(7)", maxLength: 7, nullable: true),
                    NumRevisao = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    Email = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    PrazoValidade = table.Column<int>(type: "int", nullable: true),
                    TempoReposicao = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    EstoqueSeguranca = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NotaMinimaCQ = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: true),
                    GeraSolOC = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    EmailInventario = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    StBloqueioInventario = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    UltDtInventario = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PeriodInventario = table.Column<int>(type: "int", nullable: true),
                    DtRefVlSugerido = table.Column<DateTime>(type: "datetime2", nullable: true),
                    StImpostoZonaFranca = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    LoteMinimo = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    SkipLoteProducao = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    StProdutoFantasma = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    UPEstocagem = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    CdContabilCpr = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    QtdEmpenhada = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    QtdAguardEntrega = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    StTpControle = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CdGrade = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    historiconf = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UPProducao2 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    UPProducao3 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    UPProducao4 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    UPProducao5 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    UPProducao6 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    CdServicoIndustrializacao = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    DtUltCustoComposicao = table.Column<DateTime>(type: "datetime2", nullable: true),
                    PercDesvioInferiorcpr = table.Column<decimal>(type: "decimal(5,2)", precision: 5, scale: 2, nullable: true),
                    PercDesvioSuperiorcpr = table.Column<decimal>(type: "decimal(5,2)", precision: 5, scale: 2, nullable: true),
                    StPCP = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    VlCustoStandard = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    DtRefCustoStandard = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IndiceCustoStandard = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    LeadTime = table.Column<decimal>(type: "decimal(8,3)", precision: 8, scale: 3, nullable: true),
                    UnidLeadTime = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PoliticaLote = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    TpNivelEstoqPCP = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    PercToleranciaVlCompra = table.Column<decimal>(type: "decimal(8,3)", precision: 8, scale: 3, nullable: true),
                    OpcCtsToleranciaVlCompra = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    NivelEstrutura = table.Column<int>(type: "int", nullable: true),
                    PendenteProcesNivelEstrutura = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    VlCustoComposicaoSTD = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    IndiceCustoComposicaoSTD = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    DtRefCustoComposicaoSTD = table.Column<DateTime>(type: "datetime2", nullable: true),
                    VlCustoServicoSTD = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    StMultiploPreDefinido = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    StDisponivelSFA = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    IndiceCustoServicoSTD = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    DtRefCustoServicoSTD = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DtRefCustoServico = table.Column<DateTime>(type: "datetime2", nullable: true),
                    VlCustoComposicao = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    IndiceCustoComposicao = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    StCertificado = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    StGeraNumSerie = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    PathNomeScrGeraNumSerie = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    CdUnidadeVolume = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    UPEstocagemPCP = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    VlSugestaoVdaSTD = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DtRefVlSugeridoSTD = table.Column<DateTime>(type: "datetime2", nullable: true),
                    StDel = table.Column<int>(type: "int", nullable: true),
                    StConsisteEstoque = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    vlipi_compra = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    stipi_compra = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    vlicms_compra = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    sticms_compra = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    politicamanufatura = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    stexigelote = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    dsingles = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    dsespanhol = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ncm = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    stli = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    StIPIAlq_Prd = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    stdumping = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    dsdumping = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    subupestocagem = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    stsubup = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    subupproducao = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    subupestocagempcp = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    extipi = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    cdsttributariaipi = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    cdsttributariapis = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    cdsttributariacofins = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    dtconsisteestoque = table.Column<DateTime>(type: "datetime2", nullable: true),
                    stativo02 = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    stativo03 = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    StEPI = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    EPI_CertificadoAprovacao = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    EPI_QtdVidaUtil = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EPI_UnidadeVidaUtil = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    epi_pathdoctreinamento = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    stopcional = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    cdsttributariaipi2 = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    cdsttributariapis2 = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    cdsttributariacofins2 = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    cdsttributaria2 = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    ipi_nt = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: true),
                    updregistro = table.Column<DateTime>(type: "datetime2", nullable: true),
                    keypaf = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    PercDesvioInferior2 = table.Column<decimal>(type: "decimal(8,3)", precision: 8, scale: 3, nullable: true),
                    PercDesvioSuperior2 = table.Column<decimal>(type: "decimal(8,3)", precision: 8, scale: 3, nullable: true),
                    PercDesvioInferior3 = table.Column<decimal>(type: "decimal(8,3)", precision: 8, scale: 3, nullable: true),
                    PercDesvioSuperior3 = table.Column<decimal>(type: "decimal(8,3)", precision: 8, scale: 3, nullable: true),
                    StToleranciaCompraBloqueio = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    Campo01 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Campo02 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Campo03 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Campo04 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Campo05 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Campo06 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListaProdAssociado = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VlCustoServicoCD = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    VlCustoServicoCIF = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    VlCustoServicoCSub = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    VlCustoMedioComposicao = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    VlCustoMedioServico = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    VlCustoMedioServicoCD = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VlCustoMedioServicoCIF = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    VlCustoMedioServicoCSub = table.Column<decimal>(type: "decimal(19,10)", precision: 19, scale: 10, nullable: true),
                    cdenquadramentolegalipi = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    cdenquadramentolegalipi2 = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    DsHtml = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    cdcest = table.Column<string>(type: "nvarchar(7)", maxLength: 7, nullable: true),
                    StUpd = table.Column<int>(type: "int", nullable: true),
                    rowversion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: true),
                    CdProdutoIndustrializacao = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    StIntegratePickingArea = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    CdUPPickingArea = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    PickingAreaAmountMin = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    PickingAmountMin_Unit = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    PickingAreaAmountLot = table.Column<decimal>(type: "decimal(19,8)", precision: 19, scale: 8, nullable: true),
                    PickingAreaAmountMin_Unit = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    StComposedKit = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    UpInspecao = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    SubUpInspecao = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    OrigemMercadoria = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    LifeCycle = table.Column<int>(type: "int", nullable: true),
                    VersionCreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    VersionEffectiveDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    VersionEffectiveByUser = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    dtexigenumserie = table.Column<DateTime>(type: "datetime2", nullable: true),
                    StJumpPacking = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    politicaConsumoLote = table.Column<int>(type: "int", nullable: true),
                    sfaId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    stupdSFA = table.Column<int>(type: "int", nullable: true),
                    StGerarFichaMPSAutomaticamente = table.Column<bool>(type: "bit", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Produto", x => new { x.VersionId, x.CdProduto, x.CdEmpresa, x.CdFilial });
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ParametroSincronizacaoProduto");

            migrationBuilder.DropTable(
                name: "Produto");
        }
    }
}
