using System;
using System.ComponentModel.DataAnnotations;

namespace TecWi_Web.Domain.Entities
{
    public class Produto
    {
        public string CdEmpresa { get; set; }
        public string CdFilial { get; set; }
        public string CdProduto { get; set; }
        public string DsVenda { get; set; }
        public string DsCompra { get; set; }
        public string CdClassifFinanc { get; set; }
        public string Unidade { get; set; }
        public string CdStTributaria { get; set; }
        public string TpTributacao { get; set; }
        public string CdClasFiscal { get; set; }
        public string CdOld { get; set; }
        public string CdBarra { get; set; }
        public decimal? PesoBruto { get; set; }
        public decimal? PesoLiq { get; set; }
        public string UnidadePeso { get; set; }
        public decimal? qtdvolume { get; set; }
        public bool? StAtivo { get; set; }
        public bool? StDesconto { get; set; }
        public bool? StEDI { get; set; }
        public bool? StKit { get; set; }
        public string UnidadeVda { get; set; }
        public string Origem { get; set; }
        public string TpProduto { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? DtDesativado { get; set; }
        public int? QtdItem { get; set; }
        public string Setor { get; set; }
        public string Estante { get; set; }
        public string Nivel { get; set; }
        public string CdGrupo { get; set; }
        public bool? StTabelaPreco { get; set; }
        public decimal? ConsumoMedio { get; set; }
        public string UnidConsMedio { get; set; }
        public float? EstoqMin { get; set; }
        public float? EstoqMax { get; set; }
        public float? EstoqEstrategico { get; set; }
        public float? EstoqReposicao { get; set; }
        public decimal? QtdAtualR { get; set; }
        public decimal? TempoMedioProducao { get; set; }
        public string UnidTempoMedio { get; set; }
        public decimal? PercDesvioInferior { get; set; }
        public decimal? PercDesvioSuperior { get; set; }
        public decimal? PercComissao { get; set; }
        public decimal? MargemLucro { get; set; }
        public decimal? PercOutrasDespesas { get; set; }
        public decimal? PercEncargoFinanc { get; set; }
        public decimal? PercFrete { get; set; }
        public decimal? PerMaoObra { get; set; }
        public decimal? VlCustoMedio { get; set; }
        public decimal? AlqICMS { get; set; }
        public decimal? AlqICMSCPA { get; set; }
        public decimal? AlqIPI { get; set; }
        public decimal? AlqIPICPA { get; set; }
        public decimal? AlqImportacao { get; set; }
        public string IndiceCustoR { get; set; }
        public string IndiceVendaR { get; set; }
        public decimal? ValorCustoR { get; set; }
        public decimal? ValorVendaR { get; set; }
        public decimal? ValorVarejo { get; set; }
        public decimal? TotalCustoMedio { get; set; }
        public string Marca { get; set; }
        public string NumDespacho { get; set; }
        public string Aduana { get; set; }
        public string PaisOrigem { get; set; }
        public string OrigemLinhaProducao { get; set; }
        public string AreaEnvolvimento { get; set; }
        public string CdCelula { get; set; }
        public int NumDiasGarantia { get; set; }
        public decimal? VlSugestaoVda { get; set; }
        public decimal? MarkUp { get; set; }
        public decimal? PercDespesaFixa { get; set; }
        public decimal? PercMargContribuicao { get; set; }
        public decimal? VlMercado { get; set; }
        public int? GiroEstoque { get; set; }
        public string CdClassifFinancCpr { get; set; }
        public string CdClasse { get; set; }
        public string CdGrupoQuimico { get; set; }
        public string CdClassTox { get; set; }
        public string Concentracao { get; set; }
        public decimal? PercPromocao { get; set; }
        public string opcpromocao { get; set; }
        public decimal? VlCustoServico { get; set; }
        public string IndiceCustoServico { get; set; }
        public string Embalagem { get; set; }
        public string StExigeNumSerie { get; set; }
        public string CdContabil { get; set; }
        public string StPrePedido { get; set; }
        public DateTime? DtUltCompra { get; set; }
        public string CdFornecPadrao { get; set; }
        public string NumRevisao { get; set; }
        public string Email { get; set; }
        public int? PrazoValidade { get; set; }
        public decimal? TempoReposicao { get; set; }
        public decimal? EstoqueSeguranca { get; set; }
        public string NotaMinimaCQ { get; set; }
        public string GeraSolOC { get; set; }
        public string EmailInventario { get; set; }
        public string StBloqueioInventario { get; set; }
        public DateTime? UltDtInventario { get; set; }
        public int? PeriodInventario { get; set; }
        public DateTime? DtRefVlSugerido { get; set; }
        public string StImpostoZonaFranca { get; set; }
        public decimal? LoteMinimo { get; set; }
        public decimal? SkipLoteProducao { get; set; }
        public string StProdutoFantasma { get; set; }
        public string UPEstocagem { get; set; }
        public string CdContabilCpr { get; set; }
        public decimal? QtdEmpenhada { get; set; }
        public decimal? QtdAguardEntrega { get; set; }
        public string StTpControle { get; set; }
        public string CdGrade { get; set; }
        public string historiconf { get; set; }
        public string UPProducao2 { get; set; }
        public string UPProducao3 { get; set; }
        public string UPProducao4 { get; set; }
        public string UPProducao5 { get; set; }
        public string UPProducao6 { get; set; }
        public string CdServicoIndustrializacao { get; set; }
        public DateTime? DtUltCustoComposicao { get; set; }
        public decimal? PercDesvioInferiorcpr { get; set; }
        public decimal? PercDesvioSuperiorcpr { get; set; }
        public string StPCP { get; set; }
        public decimal? VlCustoStandard { get; set; }
        public DateTime? DtRefCustoStandard { get; set; }
        public string IndiceCustoStandard { get; set; }
        public decimal? LeadTime { get; set; }
        public string UnidLeadTime { get; set; }
        public string PoliticaLote { get; set; }
        public string TpNivelEstoqPCP { get; set; }
        public decimal? PercToleranciaVlCompra { get; set; }
        public string OpcCtsToleranciaVlCompra { get; set; }
        public int? NivelEstrutura { get; set; }
        public string PendenteProcesNivelEstrutura { get; set; }
        public decimal? VlCustoComposicaoSTD { get; set; }
        public string IndiceCustoComposicaoSTD { get; set; }
        public DateTime? DtRefCustoComposicaoSTD { get; set; }
        public decimal? VlCustoServicoSTD { get; set; }
        public string StMultiploPreDefinido { get; set; }
        public string StDisponivelSFA { get; set; }
        public string IndiceCustoServicoSTD { get; set; }
        public DateTime? DtRefCustoServicoSTD { get; set; }
        public DateTime? DtRefCustoServico { get; set; }
        public decimal? VlCustoComposicao { get; set; }
        public string IndiceCustoComposicao { get; set; }
        public string StCertificado { get; set; }
        public string StGeraNumSerie { get; set; }
        public string PathNomeScrGeraNumSerie { get; set; }
        public string CdUnidadeVolume { get; set; }
        public string UPEstocagemPCP { get; set; }
        public decimal? VlSugestaoVdaSTD { get; set; }
        public DateTime? DtRefVlSugeridoSTD { get; set; }
        public int? StDel { get; set; }
        public string StConsisteEstoque { get; set; }
        public decimal? vlipi_compra { get; set; }
        public string stipi_compra { get; set; }
        public decimal? vlicms_compra { get; set; }
        public string sticms_compra { get; set; }
        public string politicamanufatura { get; set; }
        public string stexigelote { get; set; }
        public string dsingles { get; set; }
        public string dsespanhol { get; set; }
        public string ncm { get; set; }
        public string stli { get; set; }
        public string StIPIAlq_Prd { get; set; }
        public string stdumping { get; set; }
        public string dsdumping { get; set; }
        public string subupestocagem { get; set; }
        public string stsubup { get; set; }
        public string subupproducao { get; set; }
        public string subupestocagempcp { get; set; }
        public string extipi { get; set; }
        public string cdsttributariaipi { get; set; }
        public string cdsttributariapis { get; set; }
        public string cdsttributariacofins { get; set; }
        public DateTime? dtconsisteestoque { get; set; }
        public string stativo02 { get; set; }
        public string stativo03 { get; set; }
        public string StEPI { get; set; }
        public string EPI_CertificadoAprovacao { get; set; }
        public string EPI_QtdVidaUtil { get; set; }
        public string EPI_UnidadeVidaUtil { get; set; }
        public string epi_pathdoctreinamento { get; set; }
        public string stopcional { get; set; }
        public string cdsttributariaipi2 { get; set; }
        public string cdsttributariapis2 { get; set; }
        public string cdsttributariacofins2 { get; set; }
        public string cdsttributaria2 { get; set; }
        public string ipi_nt { get; set; }
        public DateTime? updregistro { get; set; }
        public string keypaf { get; set; }
        public decimal? PercDesvioInferior2 { get; set; }
        public decimal? PercDesvioSuperior2 { get; set; }
        public decimal? PercDesvioInferior3 { get; set; }
        public decimal? PercDesvioSuperior3 { get; set; }
        public string StToleranciaCompraBloqueio { get; set; }
        public string Campo01 { get; set; }
        public string Campo02 { get; set; }
        public string Campo03 { get; set; }
        public string Campo04 { get; set; }
        public string Campo05 { get; set; }
        public string Campo06 { get; set; }
        public string ListaProdAssociado { get; set; }
        public decimal? VlCustoServicoCD { get; set; }
        public decimal? VlCustoServicoCIF { get; set; }
        public decimal? VlCustoServicoCSub { get; set; }
        public decimal? VlCustoMedioComposicao { get; set; }
        public decimal? VlCustoMedioServico { get; set; }
        public decimal? VlCustoMedioServicoCD { get; set; }
        public decimal? VlCustoMedioServicoCIF { get; set; }
        public decimal? VlCustoMedioServicoCSub { get; set; }
        public string cdenquadramentolegalipi { get; set; }
        public string cdenquadramentolegalipi2 { get; set; }
        public string DsHtml { get; set; }
        public string cdcest { get; set; }
        public int? StUpd { get; set; }
        [Timestamp]
        public byte[] rowversion { get; set; }
        public string CdProdutoIndustrializacao { get; set; }
        public string StIntegratePickingArea { get; set; }
        public string CdUPPickingArea { get; set; }
        public decimal? PickingAreaAmountMin { get; set; }
        public string PickingAmountMin_Unit { get; set; }
        public decimal? PickingAreaAmountLot { get; set; }
        public string PickingAreaAmountMin_Unit { get; set; }
        public string StComposedKit { get; set; }
        public string UpInspecao { get; set; }
        public string SubUpInspecao { get; set; }
        public string OrigemMercadoria { get; set; }
        public string VersionId { get; set; }
        public int? LifeCycle { get; set; }
        public DateTime? VersionCreatedDate { get; set; }
        public DateTime? VersionEffectiveDate { get; set; }
        public string VersionEffectiveByUser { get; set; }
        public DateTime? dtexigenumserie { get; set; }
        public string StJumpPacking { get; set; }
        public int? politicaConsumoLote { get; set; }
        public Guid? sfaId { get; set; }
        public int? stupdSFA { get; set; }
        public bool? StGerarFichaMPSAutomaticamente { get; set; }
    }
}
